#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$arguments = $_SERVER['argv'];
if (($arguments[1] ?? null) === 'serve' && ! in_array('--no-reload', $arguments, true)) {
	$arguments[] = '--no-reload';
	$_SERVER['argv'] = $arguments;
}

$status = $app->handleCommand(new ArgvInput);

exit($status);
